/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.Agencia;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author betthical
 */
public class VAgencia extends javax.swing.JDialog {
    private VPrincipal padre;
    private aplicacion.FachadaAplicacion fa;
    private boolean botonNuevoPulsado = false;
    /**
     * Creates new form VUsuario
     */
    public VAgencia (java.awt.Frame padre, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(padre, modal);
        this.fa = fa;
        initComponents();
        cargarAgencias();
        javax.swing.SwingUtilities.invokeLater(() -> {
        tablaAgencias.setRowSelectionInterval(0, 0);
        tablaAgencias.scrollRectToVisible(tablaAgencias.getCellRect(0, 0, true));
        });
        tablaAgencias.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        // seleccionar primeira fila por defecto

        @Override
        public void valueChanged(ListSelectionEvent event) {
            if (!event.getValueIsAdjusting()) {
                actualizarCampos();
            }
        }
    });
    }
    
    private void actualizarCampos() {
        int selectedRow = tablaAgencias.getSelectedRow();
        if (selectedRow > -1) { // hai unha fila seleccionada
            ModeloTablaAgencias modelo = (ModeloTablaAgencias) tablaAgencias.getModel();
            Agencia agencia = modelo.obtenerAgencia(selectedRow);
            if (agencia == null){
                vaciarCampos();
                return;
            }
   
            campo_ed_id.setText(String.valueOf(agencia.getIdAgencia()));
            campo_ed_nombre.setText(agencia.getNombre());
            campo_ed_localizacion.setText(agencia.getLocalizacion());
        }
    }

    private void vaciarCampos(){
        campo_ed_id.setText("");
        campo_ed_nombre.setText("");
        campo_ed_localizacion.setText("");
    }

    private void cargarAgencias(){
        ModeloTablaAgencias m = new ModeloTablaAgencias();

        java.util.List<Agencia> agencias = fa.obtenerAgencias();

        m.setFilas(agencias);
        tablaAgencias.setModel(m);    
    }

    
    private void buscarAgenciaPorId(int id){
        ModeloTablaAgencias m = new ModeloTablaAgencias();
        Agencia a = fa.buscarAgenciaPorId(id);
        
        if (a!= null){
            java.util.List<Agencia> agencias = new java.util.ArrayList<>();
            agencias.add(a);

            m.setFilas(agencias);
        }
        tablaAgencias.setModel(m);  
    }
    
    private void buscarAgenciasPorNombre(String nombre){
        ModeloTablaAgencias m = new ModeloTablaAgencias();
        java.util.List<Agencia> agencias = fa.buscarAgenciasPorNombre(nombre);
        m.setFilas(agencias);


        tablaAgencias.setModel(m);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        tablaAgencias = new javax.swing.JTable();
        boton_buscar = new javax.swing.JButton();
        etiqueta_id = new javax.swing.JLabel();
        campo_id = new javax.swing.JTextField();
        etiqueta_nombre = new javax.swing.JLabel();
        campo_nombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        etiqueta_ed_nombre = new javax.swing.JLabel();
        etiqueta_ed_id = new javax.swing.JLabel();
        campo_ed_id = new javax.swing.JTextField();
        etiqueta_ed_localizacion = new javax.swing.JLabel();
        campo_ed_localizacion = new javax.swing.JTextField();
        campo_ed_nombre = new javax.swing.JTextField();
        buttonBorrar = new javax.swing.JButton();
        buttonGuardar = new javax.swing.JButton();
        buttonNuevo = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de Astronautas");

        tablaAgencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Localizacion"
            }
        ));
        scrollPane.setViewportView(tablaAgencias);

        boton_buscar.setText("Buscar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });

        etiqueta_id.setText("ID:");

        etiqueta_nombre.setText("Nombre:");

        campo_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nombreActionPerformed(evt);
            }
        });

        etiqueta_ed_nombre.setText("Nombre");

        etiqueta_ed_id.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta_ed_id.setText("ID");

        campo_ed_id.setEditable(false);

        etiqueta_ed_localizacion.setText("Localizacion");

        campo_ed_localizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_ed_localizacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqueta_ed_id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campo_ed_id, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(etiqueta_ed_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_ed_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiqueta_ed_localizacion)
                .addGap(18, 18, 18)
                .addComponent(campo_ed_localizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_ed_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqueta_ed_id)
                    .addComponent(etiqueta_ed_nombre)
                    .addComponent(campo_ed_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqueta_ed_localizacion)
                    .addComponent(campo_ed_localizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(etiqueta_id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_id, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etiqueta_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton_buscar)
                        .addGap(16, 16, 16))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta_id)
                    .addComponent(campo_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqueta_nombre)
                    .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_buscar))
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        buttonBorrar.setText("Borrar");
        buttonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrarActionPerformed(evt);
            }
        });

        buttonGuardar.setText("Guardar");
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });

        buttonNuevo.setText("Nuevo");
        buttonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuevoActionPerformed(evt);
            }
        });

        buttonSalir.setText("Salir");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(buttonSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonNuevo)
                .addGap(18, 18, 18)
                .addComponent(buttonGuardar)
                .addGap(18, 18, 18)
                .addComponent(buttonBorrar)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBorrar)
                    .addComponent(buttonGuardar)
                    .addComponent(buttonNuevo)
                    .addComponent(buttonSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_ed_localizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_ed_localizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_ed_localizacionActionPerformed

    private void campo_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nombreActionPerformed

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed
        String nombre = campo_nombre.getText().trim();
        String id = campo_id.getText().trim();

        if (!id.isEmpty()){
            buscarAgenciaPorId(Integer.parseInt(id));
        }
        else if (!nombre.isEmpty()){
            buscarAgenciasPorNombre(nombre);
        }
        else {
            cargarAgencias();
        }
    }//GEN-LAST:event_boton_buscarActionPerformed

    private void buttonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrarActionPerformed
        // TODO add your handling code here:
        fa.borrarAgencia(Integer.parseInt(campo_ed_id.getText()));
        this.cargarAgencias();
    }//GEN-LAST:event_buttonBorrarActionPerformed

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void buttonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuevoActionPerformed
        // TODO add your handling code here:        
        // Borro contenido de los textFields
        campo_ed_id.setText("");
        campo_ed_localizacion.setText("");
        campo_ed_nombre.setText("");
    }//GEN-LAST:event_buttonNuevoActionPerformed

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
        // TODO add your handling code here:
        Agencia a;
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        a=new Agencia(0, campo_ed_nombre.getText(), campo_ed_localizacion.getText());
        fa.actualizarAgencia(a);
        
        this.cargarAgencias();
    }//GEN-LAST:event_buttonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_buscar;
    private javax.swing.JButton buttonBorrar;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JButton buttonNuevo;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JTextField campo_ed_id;
    private javax.swing.JTextField campo_ed_localizacion;
    private javax.swing.JTextField campo_ed_nombre;
    private javax.swing.JTextField campo_id;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JLabel etiqueta_ed_id;
    private javax.swing.JLabel etiqueta_ed_localizacion;
    private javax.swing.JLabel etiqueta_ed_nombre;
    private javax.swing.JLabel etiqueta_id;
    private javax.swing.JLabel etiqueta_nombre;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tablaAgencias;
    // End of variables declaration//GEN-END:variables
}
