/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.CustomException;
import aplicacion.FachadaAplicacion;
import aplicacion.TipoCuerpoCeleste;
import aplicacion.CuerpoCeleste;

/**
 *
 * @author alumnogreibd
 */
public class VAltaCuerpo extends javax.swing.JDialog {

    FachadaAplicacion fa;
    VCuerpoCeleste padre;

    public VAltaCuerpo(java.awt.Frame parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLabel = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        ubicacionLabel = new javax.swing.JLabel();
        ubicacionText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        masaText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        habitabilidadCombo = new javax.swing.JCheckBox();
        tamanhoText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tempText = new javax.swing.JTextField();
        descText = new javax.swing.JTextField();
        galaxiaText = new javax.swing.JTextField();
        tipoCombo = new javax.swing.JComboBox<>();
        salirButton = new javax.swing.JButton();
        guardarButtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nombreLabel.setText("Nombre");

        ubicacionLabel.setText("Ubicacion");

        ubicacionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubicacionTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Masa");

        jLabel3.setText("Tamaño");

        habitabilidadCombo.setText("Habitabilidad");

        tamanhoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanhoTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Temperatura");

        jLabel5.setText("Descripción");

        jLabel6.setText("Galaxia");

        jLabel7.setText("Tipo");

        tipoCombo.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Estrella", "Luna", "Planeta" }));
        tipoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoComboActionPerformed(evt);
            }
        });

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        guardarButtn.setText("Guardar");
        guardarButtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(guardarButtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(salirButton)
                                                .addGap(25, 25, 25))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(galaxiaText,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel7)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(tipoCombo,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                                .createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel3)
                                                                                        .addComponent(nombreLabel))
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(nombreText,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                110,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(tamanhoText,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                110,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel4)
                                                                                                .addGap(8, 8, 8)
                                                                                                .addComponent(tempText,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        108,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(
                                                                                                        ubicacionLabel)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(
                                                                                                        ubicacionText,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        131,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        false)
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(0, 19,
                                                                                                        Short.MAX_VALUE)
                                                                                                .addComponent(jLabel2)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(masaText,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        108,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(
                                                                                                        habitabilidadCombo)
                                                                                                .addGap(0, 0,
                                                                                                        Short.MAX_VALUE))))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel5,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(descText,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        478,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addContainerGap(72, Short.MAX_VALUE)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nombreLabel)
                                        .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ubicacionLabel)
                                        .addComponent(ubicacionText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(masaText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(tamanhoText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(tempText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(habitabilidadCombo))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(descText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(galaxiaText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(salirButton)
                                        .addComponent(guardarButtn))
                                .addGap(22, 22, 22)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_guardarButtnActionPerformed
        darDeAltaCuerpo();
    }// GEN-LAST:event_guardarButtnActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salirButtonActionPerformed
        this.dispose();
    }// GEN-LAST:event_salirButtonActionPerformed

    private void tipoComboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tipoComboActionPerformed
    }// GEN-LAST:event_tipoComboActionPerformed

    private void tamanhoTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tamanhoTextActionPerformed
    }// GEN-LAST:event_tamanhoTextActionPerformed

    private void ubicacionTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ubicacionTextActionPerformed
    }// GEN-LAST:event_ubicacionTextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descText;
    private javax.swing.JTextField galaxiaText;
    private javax.swing.JButton guardarButtn;
    private javax.swing.JCheckBox habitabilidadCombo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField masaText;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreText;
    private javax.swing.JButton salirButton;
    private javax.swing.JTextField tamanhoText;
    private javax.swing.JTextField tempText;
    private javax.swing.JComboBox<String> tipoCombo;
    private javax.swing.JLabel ubicacionLabel;
    private javax.swing.JTextField ubicacionText;
    // End of variables declaration//GEN-END:variables

    public void darDeAltaCuerpo() {
        if (fa.getSudo()) {
            try {
                String nombre = nombreText.getText();
                TipoCuerpoCeleste tipo;
                if (nombre.isEmpty()) {
                    throw new CustomException("Debe rellenarse el nombre.");
                }
                String ubic = ubicacionText.getText();
                if (ubic.isEmpty()) {
                    throw new CustomException("Debe rellenarse la ubicacion.");
                }
                String desc = descText.getText();
                if (desc.isEmpty()) {
                    throw new CustomException("Debe rellenarse la descripcion.");
                }
                Float masa = Float.parseFloat(masaText.getText());
                if (masa < 0) {
                    throw new CustomException("La masa debe ser mayor que cero.");
                }
                Float temp = Float.parseFloat(tempText.getText());
                Float tamanho = Float.parseFloat(tamanhoText.getText());
                if (tamanho < 0) {
                    throw new CustomException("El tamanho debe ser mayor que cero.");
                }
                if (tipoCombo.getSelectedItem().equals("Seleccione:")) {
                    throw new CustomException("Debe rellenarse con un valor valido.");
                } else {
                    tipo = TipoCuerpoCeleste.valueOf((String) tipoCombo.getSelectedItem());
                }
                String galax = galaxiaText.getText();
                if (galax.isEmpty()) {
                    throw new CustomException("Debe rellenarse la galaxia.");
                }
                Boolean habitabilidad = habitabilidadCombo.isSelected();
                CuerpoCeleste nuevo = new CuerpoCeleste(nombre, tipo, ubic, habitabilidad, masa, tamanho, temp, desc,
                        galax);
                fa.darDeAltaCuerpo(nuevo);

            } catch (CustomException exception) {
                fa.muestraExcepcion(exception.getMessage());
            } catch (IllegalArgumentException ilegal) {
                fa.muestraExcepcion("Es necesario rellenar el tipo de cuerpo");
            }
        } else {
            fa.muestraExcepcion("Los usuarios normales no tienen permiso para anhadir cuerpos");
        }
    }

}
