/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.*;
import java.util.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author alumnogreibd
 */
public class VArticulo extends javax.swing.JDialog {
    
    FachadaAplicacion fa;
    List<Articulo> articulos;

    /**
     * Creates new form VArticulo
     */
    public VArticulo(java.awt.Frame parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
        
        buscarArticulos();
        seleccionarPrimero();
        
        if (fa.getUsuarioActual() instanceof Cientifico){
            jTextFieldAutor.setEditable(false);
        }
        else if (!(fa.getUsuarioActual() instanceof Administrador)){
            jTextFieldAutor.setEditable(false);
            jTextFieldID.setEditable(false);
            selectCuerpo.setEditable(false);
            jTextFieldFecha.setEditable(false);
            jTextFieldNumPaginas.setEditable(false);
            jTextAreaDescripcion.setEditable(false);
            jButtonGuardar.setVisible(false);
            jButtonNuevo.setVisible(false);
            jButtonModificar.setVisible(false);
            jButtonBorrar.setVisible(false);
        }
        cargarCuerpos();
    }

            private void cargarCuerpos(){
        ArrayList<CuerpoCeleste> listaCuerpos = (ArrayList<CuerpoCeleste>) fa.obtenerCuerpos("");

        ArrayList<String> nombresCuerpos = new ArrayList<>();
        nombresCuerpos.add("<Seleccione>"); 
        for (CuerpoCeleste c : listaCuerpos)
            nombresCuerpos.add(c.getNombreCuerpoCeleste());
        
        selectCuerpo.setModel(new DefaultComboBoxModel<>(nombresCuerpos.toArray(new String[0])));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNumPaginas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonNuevo = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaArticulo = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        selectCuerpo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Artículos");

        jLabel1.setText("Artículos:");

        jLabel2.setText("Autor:");

        jLabel3.setText("Cuerpo:");

        jLabel4.setText("Fecha publicación:");

        jLabel5.setText("Num Páginas:");

        jLabel6.setText("Descripción:");

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabel7.setText("ID");

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        tablaArticulo.setModel(new ModeloTablaArticulo());
        tablaArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaArticuloMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaArticulo);

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        selectCuerpo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Hoy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(jScrollPane1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButtonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(selectCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldNumPaginas)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(selectCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldNumPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonGuardar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        // TODO add your handling code here:
        if (fa.getUsuarioActual() instanceof Cientifico){
              jTextFieldAutor.setText(fa.getUsuarioActual().getIdUsuario());
        }
        else
            jTextFieldAutor.setText("");
        jTextFieldID.setText("");
        selectCuerpo.setSelectedItem("<Seleccione>");
        jTextFieldFecha.setText("");
        jTextFieldNumPaginas.setText("");
        jTextAreaDescripcion.setText("");
        jButtonGuardar.setEnabled(true);
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        
        if (selectCuerpo.getSelectedItem().equals("<Seleccione>")){
            fa.muestraExcepcion("Seleccione un cuerpo celeste.");
            return;
        }
       try {
        Articulo a = new Articulo(
                
            LocalDate.parse(jTextFieldFecha.getText(), DateTimeFormatter.ISO_LOCAL_DATE),
            jTextFieldAutor.getText(), 
            (String) selectCuerpo.getSelectedItem(),
            jTextAreaDescripcion.getText(),
            Integer.parseInt(jTextFieldNumPaginas.getText())
                
           
        );
                fa.guardarArticulo(a);

        jButtonBorrar.setEnabled(true);

        // Limpiar los campos de texto
        jTextFieldID.setText("");
        jTextFieldID.setEditable(false);
        jTextFieldAutor.setText("");
        selectCuerpo.setSelectedItem("<Seleccione>");
        jTextFieldFecha.setText("");
        jTextFieldNumPaginas.setText("");
        jTextAreaDescripcion.setText("");
       }
       catch (Exception e){
           fa.muestraExcepcion("Verifica el contenido de los campos. La fecha debe estar en formato YYYY-MM-DD y el nº de páginas debe ser numérico.");
           return;
       }



        buscarArticulos();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
                if (selectCuerpo.getSelectedItem().equals("<Seleccione>")){
            fa.muestraExcepcion("Seleccione un cuerpo celeste.");
            return;
        }
        Articulo a = new Articulo(
            Integer.parseInt(jTextFieldID.getText()),
            LocalDate.parse(jTextFieldFecha.getText(), DateTimeFormatter.ISO_LOCAL_DATE),
            jTextFieldAutor.getText(), 
            (String) selectCuerpo.getSelectedItem(),
            jTextAreaDescripcion.getText(),
            Integer.parseInt(jTextFieldNumPaginas.getText())
        );

        fa.modificarArticulo(a);

        jButtonBorrar.setEnabled(true);

        // Limpiar los campos de texto
        jTextFieldID.setText("");
        jTextFieldID.setEditable(false);
        jTextFieldAutor.setText("");
        selectCuerpo.setSelectedItem("<Seleccione>");
        jTextFieldFecha.setText("");
        jTextFieldNumPaginas.setText("");
        jTextAreaDescripcion.setText("");

        buscarArticulos();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
        Articulo a = new Articulo(
            Integer.parseInt(jTextFieldID.getText()),
            LocalDate.parse(jTextFieldFecha.getText(), DateTimeFormatter.ISO_LOCAL_DATE),
            jTextFieldAutor.getText(), 
            (String) selectCuerpo.getSelectedItem(),
            jTextAreaDescripcion.getText(),
            Integer.parseInt(jTextFieldNumPaginas.getText())
        );

        fa.borrarArticulo(a);

        // Limpiar los campos de texto
        jTextFieldID.setText("");
        jTextFieldID.setEditable(false);
        jTextFieldAutor.setText("");
        selectCuerpo.setSelectedItem("<Seleccione>");
        jTextFieldFecha.setText("");
        jTextFieldNumPaginas.setText("");
        jTextAreaDescripcion.setText("");

        buscarArticulos();
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tablaArticulo.getSelectedRow();
        
        if (filaSeleccionada != -1) {
            
            Articulo a = articulos.get(filaSeleccionada);
            
            jTextFieldID.setText(String.valueOf(a.getId()));
            jTextFieldID.setEditable(false);
            jTextFieldAutor.setText(a.getAutor());
            selectCuerpo.setSelectedItem(a.getCuerpoCeleste());
            jTextFieldFecha.setText(a.getFechaPublicacion().toString());
            jTextFieldNumPaginas.setText(String.valueOf(a.getNumPaginas()));
            jTextAreaDescripcion.setText(a.getDescripcion());
        }
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void tablaArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaArticuloMouseClicked
        // TODO add your handling code here:
                int filaSeleccionada = tablaArticulo.getSelectedRow();
        
        if (filaSeleccionada != -1) {
            
            Articulo a = articulos.get(filaSeleccionada);
            
            jTextFieldID.setText(String.valueOf(a.getId()));
            jTextFieldID.setEditable(false);
            jTextFieldAutor.setText(a.getAutor());
            selectCuerpo.setSelectedItem(a.getCuerpoCeleste());
            jTextFieldFecha.setText(a.getFechaPublicacion().toString());
            jTextFieldNumPaginas.setText(String.valueOf(a.getNumPaginas()));
            jTextAreaDescripcion.setText(a.getDescripcion());
        }
    }//GEN-LAST:event_tablaArticuloMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   java.time.LocalDate hoy = java.time.LocalDate.now();
    jTextFieldFecha.setText(hoy.toString()); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void seleccionarPrimero() {
    
        if (tablaArticulo.getRowCount() == 0) {
            return; // Si está vacía, salir del método
        }

        int filaSeleccionada = 0;

        Articulo a = articulos.get(filaSeleccionada);

        // Rellenar los campos de la interfaz con los datos del artículo
        jTextFieldID.setText(String.valueOf(a.getId()));
        jTextFieldID.setEditable(false);
        jTextFieldAutor.setText(a.getAutor());
        selectCuerpo.setSelectedItem(a.getCuerpoCeleste());
        jTextFieldFecha.setText(a.getFechaPublicacion().toString());
        jTextFieldNumPaginas.setText(String.valueOf(a.getNumPaginas()));
        jTextAreaDescripcion.setText(a.getDescripcion());
    }
    
    private void buscarArticulos() {
    
        articulos = fa.obtenerTodosLosArticulos();
        ModeloTablaArticulo mta = (ModeloTablaArticulo) tablaArticulo.getModel();
        mta.setFilas(articulos);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNumPaginas;
    private javax.swing.JComboBox<String> selectCuerpo;
    private javax.swing.JTable tablaArticulo;
    // End of variables declaration//GEN-END:variables
}
