/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.EntradaForo;

/**
 *
 * @author alumnogreibd
 */
public class VCategoria extends javax.swing.JDialog {

    private VPrincipal padre;
    private aplicacion.FachadaAplicacion fa;
    private aplicacion.Usuario autor;
    private aplicacion.EntradaForo entrada = null;
    /**
     * Creates new form VCategoria
     */
    public VCategoria(java.awt.Frame padre, boolean modal, aplicacion.FachadaAplicacion fa, aplicacion.Usuario autor) {
        super(padre, modal);
        this.fa = fa;
        this.padre = (VPrincipal) padre;
        this.autor = autor;

        initComponents();

        campoTextoForo.setText("");
        campoTituloForo.setText("");

    }

    public VCategoria(java.awt.Frame padre, boolean modal, aplicacion.FachadaAplicacion fa, aplicacion.Usuario autor,
            EntradaForo entrada) {
        super(padre, modal);
        this.fa = fa;
        this.padre = (VPrincipal) padre;
        this.autor = autor;
        this.entrada = entrada;

        initComponents();

        campoTextoForo.setText(entrada.getContenido());
        campoTituloForo.setText(entrada.getTitulo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campoTituloForo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoTextoForo = new javax.swing.JTextArea();
        botonGuardarForo = new javax.swing.JButton();
        botonVolverForo = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de categorías");

        jLabel4.setText("Título:");

        campoTextoForo.setColumns(20);
        campoTextoForo.setRows(5);
        jScrollPane1.setViewportView(campoTextoForo);

        botonGuardarForo.setText("Guardar");

        botonVolverForo.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(campoTituloForo))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(botonGuardarForo)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(botonVolverForo))
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 555,
                                                                Short.MAX_VALUE))))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(campoTituloForo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(botonGuardarForo)
                                        .addComponent(botonVolverForo))
                                .addContainerGap(8, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_campoNombreActionPerformed

    private void botonAñadirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonAñadirActionPerformed

    }// GEN-LAST:event_botonAñadirActionPerformed

    private void campoDescripcionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoDescripcionActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_campoDescripcionActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonBorrarActionPerformed
        if (this.entrada != null) {
            fa.eliminarEntrada(this.autor, entrada.getNumEntrada());
        }
        

    }// GEN-LAST:event_botonBorrarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }// GEN-LAST:event_botonSalirActionPerformed

    private
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        // </editor-fold>

        // </editor-fold>

        // </editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarForo;
    private javax.swing.JButton botonVolverForo;
    private javax.swing.JTextArea campoTextoForo;
    private javax.swing.JTextField campoTituloForo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables


    
    private void guardarEntrada() {
        String titulo = campoTituloForo.getText();
        String contenido = campoTextoForo.getText();

        if (this.entrada == null) {
            fa.nuevaEntrada(autor, titulo, contenido);
        } else {
            fa.modificarEntrada(autor, titulo, contenido, this.entrada.getNumEntrada());
        }

        this.dispose();
    }

}
