/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.FachadaAplicacion;
import aplicacion.Galaxia;
import aplicacion.CustomException;
import aplicacion.TipoGalaxia;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author alumnogreibd
 */
public class VGalaxia extends javax.swing.JDialog {

    private VPrincipal padre;
    FachadaAplicacion fa;
    
    public VGalaxia(java.awt.Frame parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
                ModeloTablaGalaxias m = (ModeloTablaGalaxias) tablaGalaxias.getModel();

        tablaGalaxias.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent evt) {
                colocarInformacionSeleccionada(m);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaGalaxias = new javax.swing.JTable();
        nombreGalaxia = new javax.swing.JLabel();
        nombreGalaxiaText = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        borrarButtn = new javax.swing.JButton();
        guardarButtn = new javax.swing.JButton();
        nuevoButton = new javax.swing.JButton();
        descModifText = new javax.swing.JTextField();
        descripcionModif = new javax.swing.JLabel();
        ubicacionModifText = new javax.swing.JTextField();
        ubicacionModif = new javax.swing.JLabel();
        tiposGalaxia = new javax.swing.JComboBox<>();
        salirButtn = new javax.swing.JButton();
        nombreGalaxiaModifText = new javax.swing.JTextField();
        nombreGalaxiaModif = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaGalaxias.setModel(new ModeloTablaGalaxias());
        jScrollPane1.setViewportView(tablaGalaxias);

        nombreGalaxia.setText("Nombre");

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        borrarButtn.setText("Borrar");
        borrarButtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtnActionPerformed(evt);
            }
        });

        guardarButtn.setText("Guardar");
        guardarButtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtnActionPerformed(evt);
            }
        });

        nuevoButton.setText("Nuevo");
        nuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoButtonActionPerformed(evt);
            }
        });

        descModifText.setMaximumSize(new java.awt.Dimension(617, 2147483647));
        descModifText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descModifTextActionPerformed(evt);
            }
        });

        descripcionModif.setText("Descripción");

        ubicacionModifText.setMaximumSize(new java.awt.Dimension(275, 27));

        ubicacionModif.setText("Ubicación");

        tiposGalaxia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona:", "Espiral", "Irregular", "Eliptica" }));
        tiposGalaxia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiposGalaxiaActionPerformed(evt);
            }
        });

        salirButtn.setText("Salir");

        nombreGalaxiaModifText.setEditable(false);

        nombreGalaxiaModif.setText("Nombre");

        jLabel1.setText("Tipo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nuevoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarButtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrarButtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salirButtn)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(descripcionModif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descModifText, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nombreGalaxiaModif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreGalaxiaModifText, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tiposGalaxia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(ubicacionModif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ubicacionModifText, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubicacionModifText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreGalaxiaModif)
                    .addComponent(nombreGalaxiaModifText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiposGalaxia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubicacionModif)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descModifText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcionModif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salirButtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardarButtn)
                            .addComponent(borrarButtn)
                            .addComponent(nuevoButton))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreGalaxia)
                                .addGap(18, 18, 18)
                                .addComponent(nombreGalaxiaText, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buscarButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreGalaxia)
                    .addComponent(nombreGalaxiaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoButtonActionPerformed
        VAltaGalaxia dialog = new VAltaGalaxia(new javax.swing.JFrame(), true, fa);

        dialog.setVisible(true);     
    }//GEN-LAST:event_nuevoButtonActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
       buscarGalaxias();
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void borrarButtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtnActionPerformed
        borrarGalaxia();
    }//GEN-LAST:event_borrarButtnActionPerformed

    private void guardarButtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtnActionPerformed
       modificarGalaxia();
    }//GEN-LAST:event_guardarButtnActionPerformed

    private void descModifTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descModifTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descModifTextActionPerformed

    private void tiposGalaxiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiposGalaxiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiposGalaxiaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarButtn;
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField descModifText;
    private javax.swing.JLabel descripcionModif;
    private javax.swing.JButton guardarButtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreGalaxia;
    private javax.swing.JLabel nombreGalaxiaModif;
    private javax.swing.JTextField nombreGalaxiaModifText;
    private javax.swing.JTextField nombreGalaxiaText;
    private javax.swing.JButton nuevoButton;
    private javax.swing.JButton salirButtn;
    private javax.swing.JTable tablaGalaxias;
    private javax.swing.JComboBox<String> tiposGalaxia;
    private javax.swing.JLabel ubicacionModif;
    private javax.swing.JTextField ubicacionModifText;
    // End of variables declaration//GEN-END:variables

private void buscarGalaxias() {
        ModeloTablaGalaxias m;

        m = (ModeloTablaGalaxias) tablaGalaxias.getModel();

        m.setFilas(fa.obtenerGalaxia(nombreGalaxiaText.getText()));
        if (m.getRowCount() > 0) {

            tablaGalaxias.setRowSelectionInterval(0, 0);
            colocarInformacionSeleccionada(m);

        } else {
            guardarButtn.setEnabled(false);
            borrarButtn.setEnabled(false);
        }
    }

 private void colocarInformacionSeleccionada(ModeloTablaGalaxias m) {

        if (tablaGalaxias.getSelectedRow() >= 0) {
            Galaxia seleccionado = m.obtenerGalaxia(tablaGalaxias.getSelectedRow());

            nombreGalaxiaModifText.setText(seleccionado.getNombreGalaxia());
            ubicacionModifText.setText(seleccionado.getUbicacionGalaxia());
            descModifText.setText(seleccionado.getDescGalaxia());
            tiposGalaxia.setSelectedItem(seleccionado.getTipoGalaxia().name());
            guardarButtn.setEnabled(true);
            borrarButtn.setEnabled(true);
        }
    }

    private void modificarGalaxia() {
        if (fa.getSudo()) {
            try {
                String nombreGalaxia = nombreGalaxiaModifText.getText();
                String ubicacion = ubicacionModifText.getText();
                String desc = descModifText.getText();
                TipoGalaxia tipo;
                if (ubicacion.isEmpty()) {
                    throw new CustomException("Debe rellenarse la ubicacion.");
                }
                if (desc.isEmpty()) {
                    throw new CustomException("Debe rellenarse la el campo descripcion.");
                }
                if(tiposGalaxia.getSelectedItem().equals("Selecciona:")){
                    throw new CustomException("Debe rellenarse con un valor valido.");
                }
                else{
                    tipo = TipoGalaxia.valueOf((String) tiposGalaxia.getSelectedItem());}
                Galaxia modificado = new Galaxia(nombreGalaxia, tipo, ubicacion, desc);
                fa.modificarGalaxia(modificado);

                buscarButton.doClick();
                ModeloTablaGalaxias m = (ModeloTablaGalaxias) tablaGalaxias.getModel();
                int index = 0;
                for (int i = 0; i < m.getGalaxia().size(); i++) {
                    if (m.getGalaxia().get(i).getNombreGalaxia().equals(nombreGalaxia)) {
                        index = i;
                    }
                }
                tablaGalaxias.setRowSelectionInterval(index, index);

            } catch (CustomException exception) {
                fa.muestraExcepcion(exception.getMessage());
            } catch (IllegalArgumentException ilegal) {
                fa.muestraExcepcion("Es necesario rellenar el tipo de cuerpo celeste");
            }
        } else {
            fa.muestraExcepcion("Los usuarios normales no tienen permiso para modificar cuerpos celestes");
        }

    }

    private void borrarGalaxia() { 
        if (tablaGalaxias.getSelectedRowCount() == 1) {

            ModeloTablaGalaxias m = (ModeloTablaGalaxias) tablaGalaxias.getModel();

            Galaxia seleccionado = m.obtenerGalaxia(tablaGalaxias.getSelectedRow());
            fa.borrarGalaxia(seleccionado.getNombreGalaxia());
            buscarButton.doClick();
        } else {
            fa.muestraExcepcion("Debe seleccionarse exactamente una galaxia para borrar.");
        }
    }


}
