/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.Agencia;
import aplicacion.Astronauta;
import aplicacion.HistorialAgencias;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author betthical
 */
public class VHistorialAgencias extends javax.swing.JDialog {
    private VPrincipal padre;
    private aplicacion.FachadaAplicacion fa;
    private boolean botonNuevoPulsado = false;
    int idAstronauta;
    /**
     * Creates new form VUsuario
     */
    public VHistorialAgencias (java.awt.Frame padre, boolean modal, aplicacion.FachadaAplicacion fa, int idAstronauta) {
        super(padre, modal);
        this.fa = fa;
        this.idAstronauta = idAstronauta;
        initComponents();
        cargarHistorial();

        javax.swing.SwingUtilities.invokeLater(() -> {
        });
        
    }
    
    private void cargarHistorial(){
        ModeloTablaHistorialAgencias m = new ModeloTablaHistorialAgencias();

        java.util.List<HistorialAgencias> agencias = fa.obtenerHistorialAstronauta(idAstronauta);
        for (HistorialAgencias h : agencias) {
            System.out.printf("Agencia ID: %d%n", h.getIdAgencia());
            System.out.printf("Nombre     : %s%n", h.getNombre());
            System.out.printf("Fecha inicio: %s%n", h.getFechaInicio());
            System.out.printf("Fecha fin  : %s%n", h.getFechaFin() != null ? h.getFechaFin() : "Actualidad");
            System.out.println("-------------------------------");
        }

        m.setFilas(agencias);
        tablaHistorial.setModel(m);    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de Astronautas");

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Fecha Inicio", "Fecha Fin"
            }
        ));
        jScrollPane1.setViewportView(tablaHistorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_ed_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_ed_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_ed_idActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHistorial;
    // End of variables declaration//GEN-END:variables
}
