/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/*
 * VLibro.java
 *
 * Created on 16-feb-2011, 18:17:07
 */

package gui;

import aplicacion.Libro;
import aplicacion.Ejemplar;

/**
 *
 * @author basesdatos
 */
public class VLibro extends javax.swing.JDialog {

     private Integer idLibro;
     private java.util.List<Integer> ejemplaresBorrados;
     private VPrincipal padre;
     private aplicacion.FachadaAplicacion fa;
     private boolean modoEditar=false;
    /** Creates new form VLibro */
    public VLibro(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, java.util.List<String> restoCategorias) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
        padre=(VPrincipal) parent;
        botonEliminarForo.setEnabled(false);
        this.idLibro=null;
        this.ejemplaresBorrados = new java.util.ArrayList<Integer>();



    }

    public VLibro(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Libro libro, java.util.List<String> categorias, java.util.List<String> restoCategorias) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
        padre=(VPrincipal) parent;
        idLibro=libro.getIdLibro();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        botonEliminarForo = new javax.swing.JButton();
        botonSalirForo = new javax.swing.JButton();
        botonEditarForo = new javax.swing.JButton();
        textoEntrada = new javax.swing.JLabel();
        tituloEntrada = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de libros");
        setMaximumSize(new java.awt.Dimension(620, 416));
        setMinimumSize(new java.awt.Dimension(620, 416));
        setPreferredSize(new java.awt.Dimension(620, 416));
        setResizable(false);

        botonEliminarForo.setText("Eliminar entrada");
        botonEliminarForo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarForoActionPerformed(evt);
            }
        });

        botonSalirForo.setText("Salir");
        botonSalirForo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirForoActionPerformed(evt);
            }
        });

        botonEditarForo.setText("Editar");
        botonEditarForo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarForoActionPerformed(evt);
            }
        });

        textoEntrada.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        textoEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        tituloEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonEditarForo)
                        .addGap(10, 10, 10)
                        .addComponent(botonEliminarForo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                        .addComponent(botonSalirForo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                            .addComponent(tituloEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tituloEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalirForo)
                    .addComponent(botonEliminarForo)
                    .addComponent(botonEditarForo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirForoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirForoActionPerformed
        // TODO add your handling code here:
        padre.buscarLibros();
        this.dispose();
    }//GEN-LAST:event_botonSalirForoActionPerformed

    private void botonEliminarForoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarForoActionPerformed
        // TODO add your handling code here:
    fa.borrarLibro(idLibro);
    padre.buscarLibros();
    this.dispose();
    }//GEN-LAST:event_botonEliminarForoActionPerformed

    private void botonEditarForoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarForoActionPerformed

        
    }//GEN-LAST:event_botonEditarForoActionPerformed

    private void actualizarEjemplares(){

    }

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEditarForo;
    private javax.swing.JButton botonEliminarForo;
    private javax.swing.JButton botonSalirForo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel textoEntrada;
    private javax.swing.JLabel tituloEntrada;
    // End of variables declaration//GEN-END:variables

}
