/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.Astronauta;


/**
 *
 * @author alumnogreibd
 */
public class VMisionesAstronautas extends javax.swing.JDialog {

    private VMision padre;
    private aplicacion.FachadaAplicacion fa;
    private Integer codigoMision;
    
    public VMisionesAstronautas(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Integer codigoMision, java.util.List<Astronauta> astronautas, java.util.List<Astronauta> restoAstronautas) {
        super(parent, modal);
        this.fa = fa;
        this.codigoMision = codigoMision;
        initComponents();
        
        ModeloListaAstronautas astronautasDisponibles = new ModeloListaAstronautas();
        listaAstronautasDisponibles.setModel(astronautasDisponibles);
        astronautasDisponibles.setElementos(restoAstronautas);
        if (astronautasDisponibles.getSize()>0) {
            listaAstronautasDisponibles.setSelectedIndex(0);
            botonDerecha.setEnabled(true);
        } else botonDerecha.setEnabled(false);
        
        ModeloListaAstronautas astronautasMision = new ModeloListaAstronautas();
        listaAstronautasMision.setModel(astronautasMision);
        astronautasMision.setElementos(astronautas);
        if (astronautasMision.getSize()>0) {
            listaAstronautasMision.setSelectedIndex(0);
            botonIzquierda.setEnabled(true);
        } else botonIzquierda.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        astronautasMisionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAstronautasMision = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        astronautasDisponiblesLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAstronautasDisponibles = new javax.swing.JList<>();
        botonDerecha = new javax.swing.JButton();
        botonIzquierda = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        botonsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        astronautasMisionLabel.setText("Astronautas en la misión:");

        listaAstronautasMision.setModel(new ModeloListaAstronautas());
        jScrollPane1.setViewportView(listaAstronautasMision);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(astronautasMisionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(astronautasMisionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        astronautasDisponiblesLabel.setText("Astronautas disponibles:");

        listaAstronautasDisponibles.setModel(new ModeloListaAstronautas());
        jScrollPane2.setViewportView(listaAstronautasDisponibles);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(astronautasDisponiblesLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(astronautasDisponiblesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        botonDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/flechaD.jpg"))); // NOI18N
        botonDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDerechaActionPerformed(evt);
            }
        });

        botonIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/flechaI.jpg"))); // NOI18N
        botonIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIzquierdaActionPerformed(evt);
            }
        });

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        botonsalir.setText("Salir");
        botonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonDerecha)
                    .addComponent(botonIzquierda))
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(botonActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonsalir)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(botonDerecha)
                        .addGap(26, 26, 26)
                        .addComponent(botonIzquierda))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonActualizar)
                    .addComponent(botonsalir))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDerechaActionPerformed
        ModeloListaAstronautas astronautasDisponibles;
        ModeloListaAstronautas astronautasMision;

        astronautasDisponibles = (ModeloListaAstronautas) listaAstronautasDisponibles.getModel();
        astronautasMision = (ModeloListaAstronautas) listaAstronautasMision.getModel();
        astronautasDisponibles.nuevoElemento(astronautasMision.getElementAt(listaAstronautasMision.getSelectedIndex()));
        astronautasMision.borrarElemento(listaAstronautasMision.getSelectedIndex());
        if (astronautasMision.getSize()==0) botonIzquierda.setEnabled(false);
        else listaAstronautasMision.setSelectedIndex(0);
        listaAstronautasDisponibles.setSelectedIndex(astronautasDisponibles.getSize()-1);
        botonDerecha.setEnabled(true);
    }//GEN-LAST:event_botonDerechaActionPerformed

    private void botonIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIzquierdaActionPerformed
        ModeloListaAstronautas astronautasDisponibles;
        ModeloListaAstronautas astronautasMision;

        astronautasDisponibles = (ModeloListaAstronautas) listaAstronautasDisponibles.getModel();
        astronautasMision = (ModeloListaAstronautas) listaAstronautasMision.getModel();
        astronautasMision.nuevoElemento(astronautasDisponibles.getElementAt(listaAstronautasDisponibles.getSelectedIndex()));
        astronautasDisponibles.borrarElemento(listaAstronautasDisponibles.getSelectedIndex());
        if (astronautasDisponibles.getSize()==0) botonDerecha.setEnabled(false);
        else listaAstronautasDisponibles.setSelectedIndex(0);
        listaAstronautasMision.setSelectedIndex(astronautasMision.getSize()-1);
        botonIzquierda.setEnabled(true);
    }//GEN-LAST:event_botonIzquierdaActionPerformed

    private void botonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonsalirActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        ModeloListaAstronautas ma= (ModeloListaAstronautas)listaAstronautasMision.getModel();
        fa.actualizarAstronautasMisiones(codigoMision, ma.getElementos());
    }//GEN-LAST:event_botonActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel astronautasDisponiblesLabel;
    private javax.swing.JLabel astronautasMisionLabel;
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonDerecha;
    private javax.swing.JButton botonIzquierda;
    private javax.swing.JButton botonsalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaAstronautasDisponibles;
    private javax.swing.JList<String> listaAstronautasMision;
    // End of variables declaration//GEN-END:variables
}
