/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.Mision;
import aplicacion.Nave;
import java.time.LocalDate;

/**
 *
 * @author alumnogreibd
 */
public class VMision extends javax.swing.JDialog {

    private VPrincipal padre;
    private aplicacion.FachadaAplicacion fa;    
    // variable para cuando se llama desde la ventana de naves
    private Nave nave;
    
    /**
     * Creates new form VMision
     */
    public VMision(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
        cargarMisiones();
        this.nave = null;
    }
    // Se abre la ventana misión pero en vez de mostrar todas las misiones
    // se muestran sólo las misiones en las que participa la nave
    public VMision(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Nave nave) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
        cargarMisiones(nave);
        this.nave = nave;
        
        // Cuando la ventana sólo debe mostrar las misiones de una nave
        // no se permite modificar el campo con la id de la nave
        naveTextField.setText(nave.getIDNave().toString());
        naveTextField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTexto = new javax.swing.JPanel();
        codigoLabel = new javax.swing.JLabel();
        codigoTextField = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        fechaInicioLabel = new javax.swing.JLabel();
        fechaInicioTextField = new javax.swing.JTextField();
        fechaFinLabel = new javax.swing.JLabel();
        fechaFinTextField = new javax.swing.JTextField();
        naveLabel = new javax.swing.JLabel();
        descripcionLabel = new javax.swing.JLabel();
        descripcionTextField = new javax.swing.JTextField();
        objetivoTextField = new javax.swing.JTextField();
        objetivoLabel = new javax.swing.JLabel();
        naveTextField = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        nuevoBoton = new javax.swing.JButton();
        modificarBoton = new javax.swing.JButton();
        borrarBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();
        scrollPanelTabla = new javax.swing.JScrollPane();
        tablaMisiones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        codigoLabel.setText("Código");

        nombreLabel.setText("Nombre");

        fechaInicioLabel.setText("fechaInicio");

        fechaFinLabel.setText("fechaFin");

        naveLabel.setText("Nave");

        descripcionLabel.setText("Descripción");

        objetivoLabel.setText("Objetivo");

        javax.swing.GroupLayout panelTextoLayout = new javax.swing.GroupLayout(panelTexto);
        panelTexto.setLayout(panelTextoLayout);
        panelTextoLayout.setHorizontalGroup(
            panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(codigoLabel)
                    .addComponent(objetivoLabel)
                    .addComponent(descripcionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTextoLayout.createSequentialGroup()
                        .addGroup(panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(objetivoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(codigoTextField))
                        .addGap(18, 18, 18)
                        .addGroup(panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(naveLabel)
                            .addComponent(nombreLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTextoLayout.createSequentialGroup()
                                .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fechaInicioLabel))
                            .addGroup(panelTextoLayout.createSequentialGroup()
                                .addComponent(naveTextField)
                                .addGap(28, 28, 28)
                                .addComponent(fechaFinLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fechaFinTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(fechaInicioTextField)))
                    .addComponent(descripcionTextField))
                .addContainerGap())
        );
        panelTextoLayout.setVerticalGroup(
            panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaInicioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaInicioLabel)
                    .addComponent(codigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(objetivoLabel)
                        .addComponent(objetivoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(naveLabel))
                    .addGroup(panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(naveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fechaFinLabel)
                        .addComponent(fechaFinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcionLabel)
                    .addComponent(descripcionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nuevoBoton.setText("Nuevo");
        nuevoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBotonActionPerformed(evt);
            }
        });

        modificarBoton.setText("Modificar");
        modificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBotonActionPerformed(evt);
            }
        });

        borrarBoton.setText("Borrar");
        borrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBotonActionPerformed(evt);
            }
        });

        salirBoton.setText("Salir");
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(nuevoBoton)
                .addGap(27, 27, 27)
                .addComponent(modificarBoton)
                .addGap(33, 33, 33)
                .addComponent(borrarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salirBoton)
                .addGap(18, 18, 18))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoBoton)
                    .addComponent(modificarBoton)
                    .addComponent(borrarBoton)
                    .addComponent(salirBoton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tablaMisiones.setModel(new ModeloTablaMisiones());
        tablaMisiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMisionesMouseClicked(evt);
            }
        });
        scrollPanelTabla.setViewportView(tablaMisiones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addComponent(panelTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(scrollPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirBotonActionPerformed

    private void nuevoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBotonActionPerformed
        Mision m;
        String textoFechaFin = fechaFinTextField.getText();
        LocalDate fechaFin = null;
        if (!textoFechaFin.isEmpty()) {
            fechaFin = LocalDate.parse(textoFechaFin);
        }
        m = new Mision(Integer.parseInt(codigoTextField.getText()), nombreTextField.getText(), LocalDate.parse(fechaInicioTextField.getText()), fechaFin, descripcionTextField.getText(), Integer.parseInt(naveTextField.getText()), objetivoTextField.getText());
        fa.añadirMision(m);
        if(this.nave == null) {
            cargarMisiones();
        }
        else {
            cargarMisiones(this.nave);
        }
    }//GEN-LAST:event_nuevoBotonActionPerformed

    private void modificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBotonActionPerformed
        Mision m;
        String textoFechaFin = fechaFinTextField.getText();
        LocalDate fechaFin = null;
        if (!textoFechaFin.isEmpty()) {
            fechaFin = LocalDate.parse(textoFechaFin);
        }
        m = new Mision(Integer.parseInt(codigoTextField.getText()), nombreTextField.getText(), LocalDate.parse(fechaInicioTextField.getText()), fechaFin, descripcionTextField.getText(), Integer.parseInt(naveTextField.getText()), objetivoTextField.getText());
        fa.modificarMision(m);
        if(this.nave == null) {
            cargarMisiones();
        }
        else {
            cargarMisiones(this.nave);
        }
    }//GEN-LAST:event_modificarBotonActionPerformed

    private void borrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBotonActionPerformed
        fa.borrarMision(Integer.parseInt(codigoTextField.getText()));
        if(this.nave == null) {
            cargarMisiones();
        }
        else {
            cargarMisiones(this.nave);
        }
    }//GEN-LAST:event_borrarBotonActionPerformed

    private void tablaMisionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMisionesMouseClicked
        ModeloTablaMisiones m;
        m = (ModeloTablaMisiones) tablaMisiones.getModel();
        Mision selectedMision = m.obtenerMision(tablaMisiones.getSelectedRow());
        codigoTextField.setText(String.valueOf(selectedMision.getCodigo()));
        nombreTextField.setText(selectedMision.getNombre());
        fechaInicioTextField.setText(selectedMision.getFechaInicio().toString());
        if (selectedMision.getFechaFin() == null) {
            fechaFinTextField.setText("");
        }
        else {
            fechaFinTextField.setText(selectedMision.getFechaFin().toString());
        }
        descripcionTextField.setText(selectedMision.getDescripcion());
        naveTextField.setText(selectedMision.getNave().toString());
        objetivoTextField.setText(selectedMision.getObjetivo());
        modificarBoton.setEnabled(true);
        borrarBoton.setEnabled(true);
    }//GEN-LAST:event_tablaMisionesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarBoton;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoTextField;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JTextField descripcionTextField;
    private javax.swing.JLabel fechaFinLabel;
    private javax.swing.JTextField fechaFinTextField;
    private javax.swing.JLabel fechaInicioLabel;
    private javax.swing.JTextField fechaInicioTextField;
    private javax.swing.JButton modificarBoton;
    private javax.swing.JLabel naveLabel;
    private javax.swing.JTextField naveTextField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JButton nuevoBoton;
    private javax.swing.JLabel objetivoLabel;
    private javax.swing.JTextField objetivoTextField;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelTexto;
    private javax.swing.JButton salirBoton;
    private javax.swing.JScrollPane scrollPanelTabla;
    private javax.swing.JTable tablaMisiones;
    // End of variables declaration//GEN-END:variables

    private void cargarMisiones(){
    ModeloTablaMisiones m = new ModeloTablaMisiones();
    java.util.List<Mision> misiones = fa.obtenerMisiones();
    m.setFilas(misiones);
    tablaMisiones.setModel(m); 
    
    if (m.getRowCount() > 0) {
            tablaMisiones.setRowSelectionInterval(0, 0);
            Mision mision = m.obtenerMision(tablaMisiones.getSelectedRowCount() );
            codigoTextField.setText(String.valueOf(mision.getCodigo()));
            nombreTextField.setText(mision.getNombre());
            fechaInicioTextField.setText(mision.getFechaInicio().toString());
            if (mision.getFechaFin() == null) {
                fechaFinTextField.setText("");
            }
            else {
                fechaFinTextField.setText(mision.getFechaFin().toString());
            }
            fechaFinTextField.setText(mision.getFechaFin().toString());
            descripcionTextField.setText(mision.getDescripcion());
            naveTextField.setText(mision.getNave().toString());
            objetivoTextField.setText(mision.getObjetivo());
            modificarBoton.setEnabled(true);
            borrarBoton.setEnabled(true);
        }
        else {
            modificarBoton.setEnabled(false);
            borrarBoton.setEnabled(false);
        }
       
    }
    
    // Sobrecarga para cargar sólo las misiones de una nave en concreto
    private void cargarMisiones(Nave nave){
    ModeloTablaMisiones m = new ModeloTablaMisiones();
    java.util.List<Mision> misiones = fa.obtenerMisiones(nave);
    m.setFilas(misiones);
    tablaMisiones.setModel(m); 
    
    if (m.getRowCount() > 0) {
            tablaMisiones.setRowSelectionInterval(0, 0);
            Mision mision = m.obtenerMision(tablaMisiones.getSelectedRow() );
            codigoTextField.setText(String.valueOf(mision.getCodigo()));
            nombreTextField.setText(mision.getNombre());
            fechaInicioTextField.setText(mision.getFechaInicio().toString());
            if (mision.getFechaFin() == null) {
                fechaFinTextField.setText("");
            }
            else {
                fechaFinTextField.setText(mision.getFechaFin().toString());
            }
            descripcionTextField.setText(mision.getDescripcion());
            naveTextField.setText(mision.getNave().toString());
            objetivoTextField.setText(mision.getObjetivo());
            modificarBoton.setEnabled(true);
            borrarBoton.setEnabled(true);
        }
        else {
            modificarBoton.setEnabled(false);
            borrarBoton.setEnabled(false);
        }
       
    }
}
