/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;


/**
 *
 * @author alumnogreibd
 */
public class VPrincipal extends javax.swing.JFrame implements MouseListener{

    aplicacion.FachadaAplicacion fa;
    
    public VPrincipal(aplicacion.FachadaAplicacion fa) {
        this.fa = fa;
        initComponents();
        tablaCuerposCelestes.addMouseListener(this);
    }

        private javax.swing.JTable tablaCuerposCelestes;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cuerpoCelesteMenu = new javax.swing.JMenuItem();
        galaxiaMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jMenu1.setText("File");

        cuerpoCelesteMenu.setText("CuerposCelestes");
        cuerpoCelesteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuerpoCelesteMenuActionPerformed(evt);
            }
        });
        jMenu1.add(cuerpoCelesteMenu);

        galaxiaMenu.setText("Galaxias");
        galaxiaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galaxiaMenuActionPerformed(evt);
            }
        });
        jMenu1.add(galaxiaMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void galaxiaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galaxiaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_galaxiaMenuActionPerformed

    private void cuerpoCelesteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuerpoCelesteMenuActionPerformed
        VCuerpoCeleste dialog = new VCuerpoCeleste(new javax.swing.JFrame(), true, fa);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        dialog.setVisible(true);
    }//GEN-LAST:event_cuerpoCelesteMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cuerpoCelesteMenu;
    private javax.swing.JMenuItem galaxiaMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        ModeloTablaCuerposCelestes m;

        m = (ModeloTablaCuerposCelestes) tablaCuerposCelestes.getModel();
        if (evt.getClickCount() == 2) {
            int row = tablaCuerposCelestes.getSelectedRow();
            if (row != -1) {
                System.out.println(m.getValueAt(row, 0));
            }
        }
    }

    @Override
    public void mousePressed(MouseEvent me) {
    }

    @Override
    public void mouseReleased(MouseEvent me) {
    }

    @Override
    public void mouseEntered(MouseEvent me) {
    }

    @Override
    public void mouseExited(MouseEvent me) {
    }
}
