/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VPrincipal.java
 *
 * Created on 27-ene-2011, 10:31:24
 */

package gui;


/**
 *
 * @author basesdatos
 */
public class VPrincipal extends javax.swing.JFrame {
  
    aplicacion.FachadaAplicacion fa;
    
    /** Creates new form VPrincipal */
    public VPrincipal(aplicacion.FachadaAplicacion fa) {
        this.fa=fa;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        gestionUsuarios = new javax.swing.JMenuItem();
        Agencias = new javax.swing.JMenuItem();
        gestionAstronautas = new javax.swing.JMenuItem();
        gestionNaves = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca de Informática");
        setName("vPrincipal"); // NOI18N
        setResizable(false);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jMenu1.setText("Administración");

        gestionUsuarios.setText("Usuarios");
        gestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(gestionUsuarios);

        Agencias.setText("Agencias");
        Agencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgenciasActionPerformed(evt);
            }
        });
        jMenu1.add(Agencias);

        gestionAstronautas.setText("Astronautas");
        gestionAstronautas.setToolTipText("");
        gestionAstronautas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionAstronautasActionPerformed(evt);
            }
        });
        jMenu1.add(gestionAstronautas);

        gestionNaves.setText("Naves");
        gestionNaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionNavesActionPerformed(evt);
            }
        });
        jMenu1.add(gestionNaves);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(576, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(btnSalir)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Biblioteca Informática");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
                // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void gestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuariosActionPerformed
        fa.abrirVentanaUsuarios();
    }//GEN-LAST:event_gestionUsuariosActionPerformed

    private void gestionAstronautasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionAstronautasActionPerformed
        fa.abrirVentanaAstronautas();
    }//GEN-LAST:event_gestionAstronautasActionPerformed

    private void AgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgenciasActionPerformed
        // TODO add your handling code here:
        fa.abrirVentanaAgencias();
    }//GEN-LAST:event_AgenciasActionPerformed

    private void gestionNavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionNavesActionPerformed
        VNave vn = new VNave(this,true,fa);
        vn.setVisible(true);
    }//GEN-LAST:event_gestionNavesActionPerformed

    private void gestionMisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionMisionesActionPerformed
        fa.abrirVentanaMisiones();
        //VMision vm = new VMision(this,true,fa);
        //vm.setVisible(true);
    }//GEN-LAST:event_gestionMisionesActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Agencias;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuItem gestionAstronautas;
    private javax.swing.JMenuItem gestionNaves;
    private javax.swing.JMenuItem gestionUsuarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    public void buscarLibros(){
    }
}
