/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import aplicacion.Usuario;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;
import aplicacion.TipoUsuario;
/**
 *
 * @author alumnogreibd
 */
public class VUsuario extends javax.swing.JDialog {
    private VPrincipal padre;
    private aplicacion.FachadaAplicacion fa;
    private boolean botonNuevoPulsado = false;
    /**
     * Creates new form VUsuario
     */
    public VUsuario (java.awt.Frame padre, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(padre, modal);
        this.fa = fa;
        initComponents();
        cargarUsuarios();
         javax.swing.SwingUtilities.invokeLater(() -> {
        tablaUsuarios.setRowSelectionInterval(0, 0);
        tablaUsuarios.scrollRectToVisible(tablaUsuarios.getCellRect(0, 0, true));
        });
        tablaUsuarios.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        // seleccionar primeira fila por defecto

        @Override
        public void valueChanged(ListSelectionEvent event) {
            if (!event.getValueIsAdjusting()) {
                actualizarCampos();
            }
        }
    });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        etiqueta_id = new javax.swing.JLabel();
        campo_id = new javax.swing.JTextField();
        etiqueta_nombre = new javax.swing.JLabel();
        campo_nombre = new javax.swing.JTextField();
        boton_buscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        etiqueta_ed_nombre = new javax.swing.JLabel();
        etiqueta_ed_id = new javax.swing.JLabel();
        campo_ed_id = new javax.swing.JTextField();
        etiqueta_ed_clave = new javax.swing.JLabel();
        etiqueta_ed_email = new javax.swing.JLabel();
        campo_ed_clave = new javax.swing.JTextField();
        campo_ed_email = new javax.swing.JTextField();
        etiqueta_ed_tipo = new javax.swing.JLabel();
        etiqueta_ed_direccion = new javax.swing.JLabel();
        campo_ed_direccion = new javax.swing.JTextField();
        campo_ed_nombre = new javax.swing.JTextField();
        selec_ed_tipo = new javax.swing.JComboBox<>();
        botonNuevo = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de usuarios");

        etiqueta_id.setText("ID:");

        etiqueta_nombre.setText("Nombre:");

        campo_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nombreActionPerformed(evt);
            }
        });

        boton_buscar.setText("Buscar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqueta_id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_id)
                .addGap(18, 18, 18)
                .addComponent(etiqueta_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_buscar))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta_id)
                    .addComponent(campo_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqueta_nombre)
                    .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_buscar))
                .addGap(23, 23, 23))
        );

        etiqueta_ed_nombre.setText("Nombre");

        etiqueta_ed_id.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta_ed_id.setText("ID");

        etiqueta_ed_clave.setText(" Clave");

        etiqueta_ed_email.setText("E-mail");

        campo_ed_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_ed_claveActionPerformed(evt);
            }
        });

        etiqueta_ed_tipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta_ed_tipo.setText("Tipo");

        etiqueta_ed_direccion.setText("Dirección");

        campo_ed_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_ed_direccionActionPerformed(evt);
            }
        });

        selec_ed_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Administrador" }));
        selec_ed_tipo.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(etiqueta_ed_id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_ed_id, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etiqueta_ed_clave))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(etiqueta_ed_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campo_ed_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etiqueta_ed_email)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campo_ed_email, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(campo_ed_clave))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiqueta_ed_direccion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqueta_ed_tipo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_ed_direccion)
                    .addComponent(selec_ed_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta_ed_clave)
                    .addComponent(campo_ed_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqueta_ed_tipo)
                    .addComponent(campo_ed_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqueta_ed_id)
                    .addComponent(selec_ed_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta_ed_nombre)
                    .addComponent(etiqueta_ed_email)
                    .addComponent(campo_ed_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqueta_ed_direccion)
                    .addComponent(campo_ed_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_ed_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(botonNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonGuardar)
                        .addGap(12, 12, 12)
                        .addComponent(botonBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir)))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevo)
                    .addComponent(botonGuardar)
                    .addComponent(botonBorrar)
                    .addComponent(botonSalir))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "E-mail", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);
        if (tablaUsuarios.getColumnModel().getColumnCount() > 0) {
            tablaUsuarios.getColumnModel().getColumn(0).setResizable(false);
            tablaUsuarios.getColumnModel().getColumn(1).setResizable(false);
            tablaUsuarios.getColumnModel().getColumn(2).setResizable(false);
            tablaUsuarios.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed
    String nombre = campo_nombre.getText().trim();
    String id = campo_id.getText().trim();
    
    if (!id.isEmpty()){
        buscarUsuarioPorId(id);
    }
    else if (!nombre.isEmpty()){
        buscarUsuariosPorNombre(nombre);
    }
    else {
        cargarUsuarios();
    }

    }//GEN-LAST:event_boton_buscarActionPerformed

    private void campo_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nombreActionPerformed

    private void campo_ed_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_ed_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_ed_claveActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        if (botonNuevoPulsado){
            return;
        }
        ModeloTablaUsuarios m = (ModeloTablaUsuarios) tablaUsuarios.getModel();
        m.añadirFilaVacia();
        tablaUsuarios.setModel(m);   
        
        // selecciona a nova columna (sólo estético, se está pulsado o botón nuevo o programa non presta atención á fila seleccionada e crea siempre unha nova entrada
        
        javax.swing.SwingUtilities.invokeLater(() -> {
        tablaUsuarios.setRowSelectionInterval(m.getRowCount()-1, m.getRowCount()-1);
        tablaUsuarios.scrollRectToVisible(tablaUsuarios.getCellRect(m.getRowCount()-1, 0, true));
        });
        botonNuevoPulsado = true;
        vaciarCampos();
        
        
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void campo_ed_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_ed_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_ed_direccionActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        String id_nuevo = campo_ed_id.getText().trim();
        String clave = campo_ed_clave.getText().trim();
        String nombre = campo_ed_nombre.getText().trim();
        String direccion = campo_ed_direccion.getText().trim();
        String email = campo_ed_email.getText().trim();
        String tipoString = (String) selec_ed_tipo.getSelectedItem();

        if (id_nuevo==null || clave==null || nombre==null || direccion==null || email==null || tipoString==null) return;
        if (id_nuevo.isEmpty() || clave.isEmpty() || nombre.isEmpty() || direccion.isEmpty() || email.isEmpty() || tipoString.isEmpty()) return;
        if (botonNuevoPulsado) { // non hai unha fila seleccionada
            fa.insertarUsuario(id_nuevo, nombre, clave, email, direccion, tipoString);
        }
        else {
            int selectedRow = tablaUsuarios.getSelectedRow();
            if (selectedRow == -1)
                return; //se vas a modificar unha entrada si ou si tes que seleccionar a súa fila (se é pa crear unha nova nn é obligatorio seleccionar a nova)
            String id_previo = (String) tablaUsuarios.getValueAt(selectedRow, 0);
            fa.modificarUsuario(id_nuevo, nombre, clave, email, direccion, tipoString, id_previo);
        }
        cargarUsuarios();
        vaciarCampos();
        botonNuevoPulsado = false;
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        String id = campo_ed_id.getText().trim();
        fa.eliminarUsuario(id);
        cargarUsuarios();
    }//GEN-LAST:event_botonBorrarActionPerformed
    
    private void actualizarCampos() {
        int selectedRow = tablaUsuarios.getSelectedRow();
        if (selectedRow > -1) { // hai unha fila seleccionada
            ModeloTablaUsuarios modelo = (ModeloTablaUsuarios) tablaUsuarios.getModel();
            Usuario usuario = modelo.obtenerUsuario(selectedRow);
            if (usuario == null){
                vaciarCampos();
                return;
            }
            campo_ed_id.setText(usuario.getIdUsuario());
            campo_ed_clave.setText(usuario.getClave());
            campo_ed_nombre.setText(usuario.getNombre());
            campo_ed_direccion.setText(usuario.getDireccion());
            campo_ed_email.setText(usuario.getEmail());
            selec_ed_tipo.setSelectedItem(usuario.getTipoUsuario().toString());
        }
    }

    private void vaciarCampos(){
        campo_ed_clave.setText("");
        campo_ed_id.setText("");
        campo_ed_nombre.setText("");
        campo_ed_email.setText("");
        campo_ed_direccion.setText("");
    }

    private void cargarUsuarios(){
    ModeloTablaUsuarios m = new ModeloTablaUsuarios();
    
    java.util.List<Usuario> usuarios = fa.obtenerUsuarios();

    m.setFilas(usuarios);
    tablaUsuarios.setModel(m);    
    }
    
    private void buscarUsuarioPorId(String id){
    ModeloTablaUsuarios m = new ModeloTablaUsuarios();
    Usuario u = fa.buscarUsuarioPorId(id);
    if (u!= null){
    java.util.List<Usuario> usuarios = new java.util.ArrayList<>();
    usuarios.add(u);

    m.setFilas(usuarios);
    }
    tablaUsuarios.setModel(m);  
    }
    
    private void buscarUsuariosPorNombre(String nombre){
    ModeloTablaUsuarios m = new ModeloTablaUsuarios();
    java.util.List<Usuario> usuarios = fa.buscarUsuariosPorNombre(nombre);
    m.setFilas(usuarios);
    

    tablaUsuarios.setModel(m);  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton boton_buscar;
    private javax.swing.JTextField campo_ed_clave;
    private javax.swing.JTextField campo_ed_direccion;
    private javax.swing.JTextField campo_ed_email;
    private javax.swing.JTextField campo_ed_id;
    private javax.swing.JTextField campo_ed_nombre;
    private javax.swing.JTextField campo_id;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JLabel etiqueta_ed_clave;
    private javax.swing.JLabel etiqueta_ed_direccion;
    private javax.swing.JLabel etiqueta_ed_email;
    private javax.swing.JLabel etiqueta_ed_id;
    private javax.swing.JLabel etiqueta_ed_nombre;
    private javax.swing.JLabel etiqueta_ed_tipo;
    private javax.swing.JLabel etiqueta_id;
    private javax.swing.JLabel etiqueta_nombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> selec_ed_tipo;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
